// server/src/services/users.service.js
//
// User-facing read APIs. The headline function here is searchUsers(),
// which exposes the compound text index created in seed-mongo.js
// (skill_names: 10, role: 5, bio: 3) as a ranked search.
//
// Why a text index, not a regex scan: regex on a 50-user collection
// works fine, but on a 50,000-user collection it's a full scan O(n).
// The text index gives O(log n) lookup with stemming ("designs"
// matches "design"), tokenization, and stop-word handling for free.
// The same code that handles 50 users will handle 5 million.

const { db } = require('../db/mongo');

/**
 * Full-text search across users.
 *
 * Uses MongoDB's $text operator, which routes to the user_search_idx
 * compound text index. The index weights mean:
 *   - a query word matching a skill_name contributes 10x
 *   - a query word matching a role contributes 5x
 *   - a query word matching the bio contributes 3x
 * so "react designer" prioritises Reacts-as-skill over reacts-in-bio.
 *
 * Multi-word queries are space-separated by default = OR semantics
 * (any term match counts). Wrap in escaped quotes for an exact phrase.
 *
 * Score is exposed as a top-level field for the UI to display
 * relevance bars or sort indicators.
 */
async function searchUsers(query, { limit = 20 } = {}) {
  if (!query || !query.trim()) {
    return [];
  }

  const trimmed = query.trim();

  return db().collection('users')
    .find(
      { $text: { $search: trimmed } },
      {
        // textScore is a meta-field generated by the text index;
        // we project it so the caller can show "% match" and we can
        // sort by it.
        projection: {
          _id: 1,
          username: 1,
          role: 1,
          bio: 1,
          skills: 1,
          skill_names: 1,
          score: { $meta: 'textScore' },
        },
      }
    )
    .sort({ score: { $meta: 'textScore' } })
    .limit(limit)
    .toArray();
}

module.exports = { searchUsers };
